config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home' #route for the home page
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :users do
       resource :profile
    end
    get 'about', to: 'pages#about' #when a customer makes a GET request to /about, we want the rails app to look inside the pages controller and run its "about" action. #could also use / in fromt of about, but it is not necessary
    resources :contacts, only: :create
    get 'contact-us', to: 'contacts#new', as: 'new_contact' #set new contacts controller URL to "contact-us"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    #attributes for contact already specified in the db file
    #check schema file
    
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true #making sure all fields are filled in on the form
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  
  # If Pro user passes validations (email, password, etc.)
  # then call Stripe and tell it to set up a subscription
  # upon charging the customer's card.
  
  # Stripe responds back with customer data and we store customer.id as the
  # customer token and save the user.
  def save_with_subscription
    if valid?
      #customer is a newly created variable
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # Whitelist the following form fields so that we can process them if coming
  # from a devise sign up form. This is a security feature.
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    #GET request to /contacts-us
    #Show new contact form
    def new #views file has to correspond with this name
        @contact = Contact.new #everytime somebody pulls up the contacts form, rails will generate a new contact object
        #the @contact is an "instance variable"
    end
    
    #POST request to /contacts
    def create #method to save user input on the contact form
        @contact = Contact.new(contact_params) #contact_params is from the private field below
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments] #body is referred to as comments here as we have defined it that way below on line 24
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = @contact.errors.full_messages.join(", ")
            redirect_to new_contact_path
        end
    end
    
    private #security feature to ensure correct attributes are entered I guess?
        def contact_params
            params.required(:contact).permit(:name, :email, :comments)
        end
end

=begin 
The "def create" saves a new contact object. The if statement is run to check if
the contact message was saved, and if so redirect the user to the contact page
with a message stating that the message was sent successfully.

The else states that if the message failed to send, then send the user to the
contact form page and notify the user that the message failed to send.
=end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # GET request for / which is our home page
    def home #corresponding "home.html.erb" file can be found in the saasapp/views/pages directory
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    # GET request for about path which is our about page
    def about #corresponding "about.html.erb" file can be found in the saasapp/views/pages directory
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    # GET to /users/:user_id/profile/new
    def new
        @profile = Profile.new
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :select_plan, only: :new
    # Extend default Devise gem behaviour so that
    # users signing up with the Pro account (plan ID 2)
    # save with a special Stripe subscription function
    
    # Otherwise Devise signs up user as usual
    def create
        super do |resource|
           if params[:plan] #if there is a plan parameter in the url
               resource.plan_id = params[:plan]
               if resource.plan == 2
                  resource.save_with_subscription
              else
                  resource.save
               end
           end
        end
    end
    
    private
        def select_plan
            unless (params[:plan] == '1' || params[:plan] == '2')
                flash[:notice] = "Please select a membership plan to sign up."
                redirect_to root_url
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <h3 class="text-center">Contact Us</h3>
        
        <div class="col-md-4 col-md-offset-4">
      
            <div class="well">
                <%= form_for @contact do |f| %>
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :email %>
                        <%= f.text_field :email, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :comments %>
                        <%= f.text_area :comments, class: 'form-control' %>
                    </div>
                        <%= f.submit 'Submit', class: 'btn btn-default' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevMatch</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet"> <!--Removed http/https from the link, not needed and it makes it more flexible -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class='container'>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <%= link_to root_path, class: "navbar-brand" do  %> <!-- "/" means home directory -->
            <i class="fa fa-group"></i>
            DevMatch
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %> <!-- if statement to check if user is signed in using devise if statement "user_signed_in?" -->
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact Us", new_contact_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact Us", new_contact_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container flash-container">
      <!--for each flash message, pass in type and msg temp variables -->
      <% flash.each do |type, msg| %> <!-- for each in the flash list (success, danger as seen in the contacts_controller file). The flash list has key value pairs -->
        <%= content_tag :div, msg, class: "alert alert-#{type}" %> <!--create a div tag, pass in the message and assign it the appropriate class type, e.g. success or danger -->
      <% end %>
    </div>
    <%= yield %> <!-- This is where rails pulls in the code from the other views files, e.g. the home.html file-->
    
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-justify">
    <h1>About Us</h1>
    <br/>
    <p>We are DevMatch. Our company focuses on creating an exclusive community
    for developers and entrepreneurs to meet. When signing up to DevMatch, you 
    have a choice between two account types. These can be seen below. </p>
    
    <div class="row">
        <div class="col-lg-6 text-center">
            <h2>Basic Account</h2>
            <ul class="list-group">
                <li class="list-group-item">No cost</li>
                <li class="list-group-item">User profiles</li>
                <li class="list-group-item">Limited community access: view services with <strong>no</strong> contact information</li>
            </ul>
        </div>
        <div class="col-lg-6 text-center">
            <h2>Pro Account</h2>
            <ul class="list-group">
                <li class="list-group-item">Costs £10/month</li>
                <li class="list-group-item">User profiles</li>
                <li class="list-group-item">Full community access: view services <strong>with</strong> contact information</li>
            </ul>
        </div>
    </div>
</div>

<!--

<ul class="list-group">
  <li class="list-group-item">Cras justo odio</li>
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item">Morbi leo risus</li>
  <li class="list-group-item">Porta ac consectetur ac</li>
  <li class="list-group-item">Vestibulum at eros</li>
</ul>

-->

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid"> <!--Added this class name so we can apply css gradient to title only, not the entire page-->
                        <!-- text center is a bootstrap class name -->
                        <!-- container-fluid is also a bootstrap class name -->
    <h1>Welcome to DevMatch</h1>
    <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>
<div class="container home-signup-links">
    <div class="row">
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">Basic Membership</h2>
                <h4 class="text-center"> A free account with basic access to the community. </h4>
                <br/>
                <%= link_to "Sign up with a basic membership plan", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">Pro Membership</h2>
                <h4 class="text-center"> A paid account with full access to the community including contact information! </h4>
                <%= link_to "Sign up with a pro membership plan (£10/month)", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
            </div>
        </div>
        <div class="col-lg-12 text-center text-justify">
            <h3><strong>Welcome to DevMatch</strong></h3>
            <p>This is a fictional website, therefore no real services are offered here so do not sign up for a pro account unless you want to give me your money for doing nothing!</p>
            <p>If you are an employer, please test all the features of this web app. You can sign up for a free or paid subscription account for £10/month. You can customise your user profile and make posts. The email 
            feature also works so you can contact me from within this site. However, I rarely check my DevMatch email address for mail as this is a fictional website so please contact me using the email address provided 
            in my CV. Thanks and enjoy this web app!</p>
        </div>
    </div>
    <%= link_to "Create your profile!", new_user_profile_path(user_id: current_user.id) if user_signed_in? %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.submit "Update Profile", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Be a part of the DevMatch community and fill out your profile!</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>